STORY = {"slug": "xg_finishing", "tag": "XG STORY"}

SLIDES = [
    {"kind": "title", "label": "THE XG SIGNAL", "title": "Buy the xG. Fade the hot streak.", "highlight": "xG", "body": ["Recent xG tells you who may score next.", "A hot finishing streak does not." ]},
    {"kind": "text", "title": "xG works when games add up", "kicker": "STEP 1", "highlight": "over a full season", "body": ["One match is noisy. Goals arrive in whole numbers and luck can swing the result.", "But over a full season, goals and xG line up closely. The link is 0.93 out of 1.", "Treat xG as a season-level guide, not a one-game call."]},
    {"kind": "chart", "headline": "Over a season, xG and goals move together.", "highlight": "xG and goals", "chart": "xg_finishing/xgf_01_xg_tracks_goals.png", "caption": "One-match noise becomes a clear season signal."},
    {"kind": "text", "title": "Hot finishing does not repeat", "kicker": "STEP 2", "highlight": "almost zero", "body": ["Attackers who beat xG in one half of the season did not keep doing it in the other half.", "The relationship was almost zero: 0.03 out of 1.", "That looks like luck that comes and goes, not a steady short-term skill."]},
    {"kind": "chart", "headline": "Finishing above xG is mostly a one-off.", "highlight": "mostly a one-off", "chart": "xg_finishing/xgf_02_overperformance_noise.png", "caption": "Odd and even game halves do not line up."},
    {"kind": "text", "title": "Use the signal that lasts", "kicker": "STEP 3", "highlight": "Recent xG wins", "body": ["Recent xG ranks next-four-game goals about twice as well as recent goals do.", "It scores 0.35 versus 0.19 because it strips out finishing luck.", "Recent overperformance lands at zero. A hot streak is a mirage."]},
    {"kind": "chart", "headline": "Recent xG beats recent goals for the next four games.", "highlight": "Recent xG beats", "chart": "xg_finishing/xgf_03_signal_strength.png", "caption": "Ranking strength for future goals."},
    {"kind": "checklist", "title": "What to do this week", "kicker": "TRANSFER RULES", "highlight": "recent xG, not recent goals", "rows": ["Screen attackers on recent xG, not recent goals.", "Do not chase a hot finishing streak.", "Notice players creating chances but scoring below xG.", "Judge finishing over a season, not a month."]},
    {"kind": "closing", "title": "Keep the claim honest", "kicker": "CAVEATS + METHOD", "body": ["This is a link with future goals, not proof that xG causes goals.", "Penalties lift xG, so penalty takers can stand out for a fair reason.", "This is one season and one xG provider. Elite finishers can be exceptions.", "We used only past games, tested future goals, resampled weeks, and checked three to five game windows."], "summary": "Use xG to find repeatable chance volume, then leave room for uncertainty."},
]
