STORY = {"slug": "mean_vs_median", "tag": "FORM STORY"}

SLIDES = [
    {"kind": "title", "label": "RECENT FORM", "title": "Mean or median? It depends on the job.", "highlight": "depends on the job", "body": ["For four-gameweek ranks, they are tied.", "For exact forecasts, rare hauls change the answer." ]},
    {"kind": "text", "title": "Points are lumpy", "kicker": "STEP 1", "highlight": "one-off big hauls", "body": ["Many players score zero or one in a gameweek. A few scores are very large.", "Even among full-match players, the mean sits above the median.", "That gap is made by rare, one-off big hauls."]},
    {"kind": "chart", "headline": "Rare big hauls pull the mean away from the median.", "highlight": "Rare big hauls", "chart": "mean_vs_median/01_distribution_shapes.png", "caption": "The difference appears even among players who played."},
    {"kind": "text", "title": "Four-game summaries disagree", "kicker": "STEP 2", "highlight": "one big haul", "body": ["Over four gameweeks, median stays spiky at low whole numbers.", "Mean is smoother and shifted higher.", "One big haul can pull up the average without changing the median at all."]},
    {"kind": "chart", "headline": "Mean and median tell different four-game stories.", "highlight": "different four-game stories", "chart": "mean_vs_median/02_mean_vs_median_spread.png", "caption": "The actual recent-form feature for likely starters."},
    {"kind": "text", "title": "For ranking, they are close", "kicker": "STEP 3", "highlight": "barely distinguishable", "body": ["Both past-four-game signals have a wide relationship with the next four games.", "Their trend lines are barely distinguishable at this horizon.", "The ranking figures are 0.203 for mean and 0.215 for median."]},
    {"kind": "chart", "headline": "At four gameweeks, mean and median rank similarly.", "highlight": "rank similarly", "chart": "mean_vs_median/03_bivariate_scatter.png", "caption": "A real but weak recent-form signal either way."},
    {"kind": "text", "title": "The winner flips with the task", "kicker": "STEP 4", "highlight": "mean pulls ahead", "body": ["For ranking, mean and median tie through six games. Mean pulls ahead at seven and eight.", "For exact-point forecasts, median is more accurate at four and six games.", "There is no single best summary without naming the job first."]},
    {"kind": "chart", "headline": "Ranking and exact forecasts reward different choices.", "highlight": "different choices", "chart": "mean_vs_median/04_ranking_and_error_by_N.png", "caption": "Results change with the horizon and outcome."},
    {"kind": "text", "title": "Midfielders drive the gap", "kicker": "STEP 5", "highlight": "midfielders drive", "body": ["Pooling positions hides the main pattern.", "Midfielders create almost all of the median advantage for forecast error.", "Defenders, forwards, and keepers show little clear pattern."]},
    {"kind": "chart", "headline": "The median edge is mostly a midfielder story.", "highlight": "mostly a midfielder story", "chart": "mean_vs_median/05_position_breakdown.png", "caption": "Position mix changes the size of the effect."},
    {"kind": "text", "title": "The problem is the haul", "kicker": "STEP 6", "highlight": "erases almost all", "body": ["Cap past scores at 10 points and almost all of median's forecast-error edge disappears.", "That shows mean is not wrong. It is just exposed to rare hauls that do not repeat.", "A capped mean can catch back up, or win."]},
    {"kind": "chart", "headline": "Capping big hauls erases almost all of the median edge.", "highlight": "erases almost all", "chart": "mean_vs_median/06_mechanism_capping.png", "caption": "The mechanism is unguarded one-off scores."},
    {"kind": "checklist", "title": "Choose the stat for the job", "kicker": "WHAT TO DO", "highlight": "keep mean-based ranking", "rows": ["For four-gameweek transfer ranks, keep mean-based ranking.", "Do not switch rules for a statistical tie.", "For exact forecasts, cap extreme past scores before averaging.", "Treat a capped mean as a next step, not a tested final answer."]},
    {"kind": "closing", "title": "A context, not a verdict", "kicker": "CAVEATS + METHOD", "body": ["This is one 2025/26 season. Other seasons are not yet tested.", "These results are links, not causes of future points.", "The likely-starter gate and position mix affect the size of the result.", "We compared walk-forward four-to-eight-game windows with gameweek-block resampling."], "summary": "At N=4, keep the mean for ranks. Guard against hauls for exact forecasts."},
]
