STORY = {"slug": "points_by_position", "tag": "VALUE STORY"}

SLIDES = [
    {"kind": "title", "label": "FPL VALUE", "title": "Spend on attackers. Build the spine cheap.", "highlight": "attackers", "body": ["Forwards and midfielders score most.", "Keepers and defenders give more points for your money." ]},
    {"kind": "text", "title": "Each shirt earns points its own way", "kicker": "STEP 1", "highlight": "half of every position's points", "body": ["Minutes are the big base. The 60-minute point drip is about half of every position's score.", "Keepers earn from saves and clean sheets. Defenders add clean sheets and defending points.", "Midfielders mix goals and assists. Forwards rely on goals, which make up 31% of their points."]},
    {"kind": "chart", "headline": "The scoring mix changes with the shirt.", "highlight": "changes with the shirt", "chart": "points_by_position/pos_01_composition.png", "caption": "Where each position built its 2025/26 points."},
    {"kind": "text", "title": "Raw points are not value", "kicker": "STEP 2", "highlight": "The ranking flips", "body": ["Forwards score the most points per player but the fewest points per pound.", "Keepers and defenders score less in total, yet their lower price makes each pound work harder.", "You pay a premium for the forward goal ceiling."]},
    {"kind": "chart", "headline": "The best scorers are not the best value.", "highlight": "not the best value", "chart": "points_by_position/pos_02_absolute_vs_value.png", "caption": "Points per player and points per £1m tell different stories."},
    {"kind": "text", "title": "Defenders win the value battle", "kicker": "STEP 3", "highlight": "cheap but productive", "body": ["Regular defenders cluster above average value: cheap but productive.", "Forwards spread into higher prices, and many fall below the value line.", "Defender points are cheaper. Forward points cost a premium."]},
    {"kind": "chart", "headline": "Cheap regular defenders sit in the value zone.", "highlight": "value zone", "chart": "points_by_position/pos_03_value_scatter.png", "caption": "Regular starters only, with average value marked."},
    {"kind": "checklist", "title": "Build your budget around value", "kicker": "WHAT TO DO", "highlight": "cheap, nailed-on keeper", "rows": ["Start with a cheap, nailed-on keeper and regular defenders.", "Pay up for one or two high-ceiling attackers.", "Do not fill the squad with expensive forwards for raw points.", "Judge each shirt on the stat that earns its points."]},
    {"kind": "closing", "title": "Useful, not timeless", "kicker": "CAVEATS + METHOD", "body": ["This is one season. New defending points began in 2025/26.", "Season totals reward players who never rotate, which helps keepers look valuable.", "The value result covers regular starters with 900 or more minutes.", "We rebuilt points from official rules and matched real totals for 99.7% of rows."], "summary": "Buy cheap stability at the back, then spend selective money on attack."},
]
