STORY = {"slug": "expected_stats", "tag": "XGI STORY"}

SLIDES = [
    {"kind": "title", "label": "EXPECTED STATS", "title": "xGI helps. But only for attackers.", "highlight": "attackers", "body": ["Use expected involvement to sharpen attacker picks.", "For defenders and keepers, fixtures matter more." ]},
    {"kind": "text", "title": "One big week can fool you", "kicker": "STEP 1", "highlight": "lucky week", "body": ["Attacker points are lumpy. Most weeks are quiet, then a few huge scores arrive.", "A player can look hot after one lucky week and cold after one quiet week.", "xGI tracks chance quality and moves more smoothly than raw goals and assists."]},
    {"kind": "chart", "headline": "Weekly attacker points are lumpy by nature.", "highlight": "lumpy by nature", "chart": "expected_stats/xstat_01_points_are_lumpy.png", "caption": "Rare hauls can distort a short run of form."},
    {"kind": "text", "title": "xGI picks better attackers", "kicker": "STEP 2", "highlight": "xGI beats recent form", "body": ["xGI beats recent form when ranking attacker points over the next four gameweeks.", "Three-game form is the weakest. Five-game form improves, but xGI still leads.", "ICT is close to xGI, so you do not need both. Pick xGI."]},
    {"kind": "chart", "headline": "For attackers, xGI leads the signal test.", "highlight": "xGI leads", "chart": "expected_stats/xstat_02_signal_strength_attackers.png", "caption": "Higher bars sort future attacker points better."},
    {"kind": "text", "title": "The rule changes by position", "kicker": "STEP 3", "highlight": "lean on fixtures", "body": ["For attackers, xGI is strongest. For defenders and keepers, it is weakest.", "Defensive points rely on clean sheets, which depend heavily on the opponent.", "For defenders, lean on fixtures and expected goals conceded instead."]},
    {"kind": "chart", "headline": "xGI works for attackers, fixtures for defensive picks.", "highlight": "fixtures for defensive picks", "chart": "expected_stats/xstat_03_by_position.png", "caption": "The best signal changes by position."},
    {"kind": "text", "title": "The edge grows with time", "kicker": "STEP 4", "highlight": "both ranges stay above", "body": ["xGI adds ranking skill above recent form at four and eight gameweeks.", "Both ranges stay above the no-edge line.", "The longer horizon helps luck even out and the underlying quality show through."]},
    {"kind": "chart", "headline": "The xGI edge holds at both tested horizons.", "highlight": "holds at both", "chart": "expected_stats/xstat_04_edge_by_horizon.png", "caption": "Extra ranking skill over recent form."},
    {"kind": "text", "title": "The payoff is practical", "kicker": "STEP 5", "highlight": "form plus xGI wins", "body": ["Top-eight picks by form scored 4.55 points per game. xGI alone scored 4.83.", "Form plus xGI wins at 5.00, ahead of the 3.91 average attacker.", "xGI is an addition to form, not a replacement for it."]},
    {"kind": "chart", "headline": "Combining form and xGI earns the best top-eight return.", "highlight": "best top-eight return", "chart": "expected_stats/xstat_05_top8_payoff.png", "caption": "Average next-game points for attacker shortlists."},
    {"kind": "text", "title": "Bruno showed the gap", "kicker": "STEP 6", "highlight": "cold points but warm involvement", "body": ["Before Bruno Guimaraes' hot run, his three-game form was only 1.7 points per game.", "His involvement stayed warm. He kept reaching good spots.", "Cold points but warm involvement gave a hint that form alone missed. It was not a promise."]},
    {"kind": "chart", "headline": "Expected involvement stayed warm before Bruno's points returned.", "highlight": "stayed warm", "chart": "expected_stats/xstat_06_bruno.png", "caption": "A case study, not a guaranteed call."},
    {"kind": "checklist", "title": "Use expected stats with care", "kicker": "WHAT TO DO", "highlight": "Add xGI for attackers", "rows": ["Keep minutes, form, fixtures, and ownership in your process.", "Add xGI for attackers when form looks similar.", "Use form and xGI together, not one alone.", "Skip ICT if you already use xGI.", "For defenders and keepers, chase fixtures and low expected goals conceded."]},
    {"kind": "closing", "title": "An edge, not a promise", "kicker": "CAVEATS + METHOD", "body": ["This is one season. Treat exact effect sizes as a guide, not a law.", "xGI includes penalties, which fairly lifts penalty takers.", "The test covers players with regular minutes, the group you can choose from.", "We used only past data, tested the next four to eight games, and repeated resampled and blind checks."], "summary": "xGI can tilt attacker choices your way, especially beside recent form."},
]
