STORY = {"slug": "fdr", "tag": "FIXTURE STORY"}

SLIDES = [
    {"kind": "title", "label": "FIXTURE DIFFICULTY", "title": "Fixtures help. The home tweak does not", "highlight": "does not", "body": ["Easy runs predict more points, but it is a small edge.", "Use raw FDR as a tie-breaker." ]},
    {"kind": "text", "title": "Most fixture runs are average", "kicker": "STEP 1", "highlight": "the tails, not the norm", "body": ["For likely starters, most fixture runs sit near FDR 3.", "Truly easy and truly hard runs are the tails, not the norm.", "Points are lumpy too. Most weeks are quiet, with rare big hauls."]},
    {"kind": "chart", "headline": "Average fixtures are common. Extreme runs are rare.", "highlight": "Extreme runs are rare", "chart": "fdr/01_distribution_shapes.png", "caption": "The starting distributions for FDR and points."},
    {"kind": "text", "title": "The home tweak barely moves FDR", "kicker": "STEP 2", "highlight": "nearly indistinguishable", "body": ["Subtracting 0.1 at home and adding 0.1 away barely shifts the fixture numbers.", "The raw and adjusted distributions are nearly indistinguishable.", "That is small beside an FDR scale that swings by whole points."]},
    {"kind": "chart", "headline": "Raw and home-adjusted FDR almost overlap.", "highlight": "almost overlap", "chart": "fdr/02_raw_vs_adjusted_fdr.png", "caption": "The ±0.1 shift is tiny beside the raw scale."},
    {"kind": "text", "title": "Easy fixtures link with more points", "kicker": "STEP 3", "highlight": "easier fixtures, more points", "body": ["The scatter is wide, so fixture difficulty is a real but weak signal.", "The trend slopes the right way.", "Average points fall in a clear pattern from the easiest fixture fifth to the hardest."]},
    {"kind": "chart", "headline": "Easier upcoming fixtures link with higher points.", "highlight": "link with higher points", "chart": "fdr/03_bivariate_scatter.png", "caption": "A small effect made clearer by grouping fixture runs."},
    {"kind": "text", "title": "The edge holds from four to eight", "kicker": "STEP 4", "highlight": "every range stays below zero", "body": ["Across four to eight gameweek windows, the fixture effect remains after recent form is included.", "Every range stays below zero, away from the no-effect line.", "The effect grows a little at longer horizons as noise smooths out."]},
    {"kind": "chart", "headline": "Fixture difficulty remains a steady negative link to points.", "highlight": "steady negative link", "chart": "fdr/04_association_by_N.png", "caption": "Controlled for recent form across forward windows."},
    {"kind": "text", "title": "Defensive picks gain more", "kicker": "STEP 5", "highlight": "defenders and keepers", "body": ["All positions show the fixture link, but defenders and keepers show close to double the effect.", "Their clean-sheet points depend heavily on the opponent.", "That makes FDR a more useful tie-breaker for defensive picks."]},
    {"kind": "chart", "headline": "FDR matters most for defenders and keepers.", "highlight": "most for defenders", "chart": "fdr/05_position_breakdown.png", "caption": "Every position points in the same direction."},
    {"kind": "text", "title": "Drop the home and away tweak", "kicker": "STEP 6", "highlight": "nothing measurable", "body": ["Adjusted and raw FDR produce almost the same model result.", "Home advantage has no separate measurable effect once raw FDR is in the model.", "The simplest explanation is that the FPL rating already includes home and away."]},
    {"kind": "chart", "headline": "The ±0.1 tweak adds nothing measurable.", "highlight": "adds nothing measurable", "chart": "fdr/06_mechanism_home_away.png", "caption": "Use the plain 1 to 5 FDR rating."},
    {"kind": "checklist", "title": "Use fixtures in the right place", "kicker": "WHAT TO DO", "highlight": "as a tie-breaker", "rows": ["Use next-four-to-eight-game FDR as a tie-breaker.", "Weight it more for defenders and keepers.", "Do not make fixtures your headline transfer reason.", "Score fixtures with raw FDR. Drop the manual home and away tweak."]},
    {"kind": "closing", "title": "A small, useful edge", "kicker": "CAVEATS + METHOD", "body": ["This is one 2025/26 season. Other seasons remain untested.", "Fixtures are not randomly assigned, so this is a link, not a cause.", "The likely-starter gate and player-team mapping were checked for robustness.", "We tested likely starters over four to eight future gameweeks and controlled for recent form."], "summary": "Easy fixtures help a little. Keep the process simple and use raw FDR."},
]
