STORY = {"slug": "elite_ownership", "tag": "OWNERSHIP STORY"}

SLIDES = [
    {"kind": "title", "label": "ELITE OWNERSHIP", "title": "Trust good managers. Do not copy their picks.", "highlight": "Do not copy", "body": ["Strong managers become reliable early.", "Their ownership does not beat free signals." ]},
    {"kind": "text", "title": "Early rank is mostly luck", "kicker": "STEP 1", "highlight": "one gameweek is mostly luck", "body": ["After Gameweek 1, eventual top-1% managers sit across almost the whole rank range.", "One bad week can leave a strong manager in the millions.", "Current rank means very different things in September and March."]},
    {"kind": "chart", "headline": "Rank noise is huge at the start of the season.", "highlight": "huge at the start", "chart": "elite_ownership/eo_01_rank_noise.png", "caption": "The same strong group spreads widely before it settles."},
    {"kind": "text", "title": "Ownership is lopsided", "kicker": "STEP 2", "highlight": "a few template players", "body": ["Elite ownership piles onto a few template players. Most players are owned by hardly any strong managers.", "Future points are lopsided too. Quiet weeks are common and big hauls are rare.", "The real test is whether ownership helps predict those future points."]},
    {"kind": "chart", "headline": "Elite ownership and future points are both uneven.", "highlight": "both uneven", "chart": "elite_ownership/eo_02_ingredients.png", "caption": "Raw ingredients before the prediction test."},
    {"kind": "text", "title": "Strong managers settle by GW6 to 8", "kicker": "STEP 3", "highlight": "around Gameweek 6 to 8", "body": ["Rank starts as noise, then quickly becomes stable.", "By around Gameweek 6 to 8, current rank predicts rank four weeks later at about 0.8.", "The reference group is real early. That makes the next result more surprising."]},
    {"kind": "chart", "headline": "Manager rank becomes a reliable guide by GW6 to 8.", "highlight": "by GW6 to 8", "chart": "elite_ownership/eo_03_rank_persistence.png", "caption": "Rank persistence rises out of early-season noise."},
    {"kind": "text", "title": "Elite ownership has a weak link", "kicker": "STEP 4", "highlight": "a real upward tilt", "body": ["Players owned by more strong managers do score more on average in the next four gameweeks.", "But the cloud is huge and the relationship is gentle: Spearman is about 0.24.", "It carries some signal. The question is whether it beats free alternatives."]},
    {"kind": "chart", "headline": "Elite ownership links with points, but only weakly.", "highlight": "only weakly", "chart": "elite_ownership/eo_04_eo_vs_points.png", "caption": "A gentle trend inside a very wide cloud."},
    {"kind": "text", "title": "Plain popularity wins", "kicker": "STEP 5", "highlight": "0.284 beats 0.244", "body": ["Plain popularity scores 0.284. Elite ownership scores 0.244.", "Elite ownership only barely beats recent points, and that thin edge vanishes over eight gameweeks.", "Knowing elite picks adds nothing you cannot get from a wider free signal."]},
    {"kind": "chart", "headline": "Plain popularity beats elite ownership in the ranking test.", "highlight": "beats elite ownership", "chart": "elite_ownership/eo_05_ranking_skill.png", "caption": "Signals known last week, tested over the next four."},
    {"kind": "text", "title": "More elite makes it worse", "kicker": "STEP 6", "highlight": "never takes the lead", "body": ["Tighter elite groups pile onto the same template players and add more noise.", "Top-3% and top-10K groups lose by more, not less.", "Plain popularity leads or ties across the season. Elite ownership never takes the lead."]},
    {"kind": "chart", "headline": "A narrower elite group makes the signal weaker.", "highlight": "signal weaker", "chart": "elite_ownership/eo_06_more_elite_worse.png", "caption": "There is no gameweek where elite ownership switches on."},
    {"kind": "checklist", "title": "What to do with ownership", "kicker": "DECISION RULE", "highlight": "do not chase elite ownership", "rows": ["Trust that a strong-manager group is real from GW6 to 8.", "But do not chase elite ownership as a shortlist tool.", "Use plain popularity if you want an ownership signal.", "Keep recent points as a simple guide among likely starters."]},
    {"kind": "closing", "title": "Keep the limits visible", "kicker": "CAVEATS + METHOD", "body": ["This is one 2025/26 season and a 1,000-manager top-1% reference sample.", "The sample has survivorship, which should make copying look good, yet it still loses.", "Plain popularity here means the wider strong-manager sample, not global ownership.", "These are predictive links, not causes, using only information known up to the prior week."], "summary": "Good managers are worth respecting. Their ownership is not a special transfer signal."},
]
